[project]
name = "bluetooth-lock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bleak>=2.1.1",
    "instagram>=1.3.4",
    "openai>=2.14.0",
]
